version: "3"
services:
    app:
        container_name: vue-cloudfront-app
        restart: always
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - vcf-storage:/app/_storage
        depends_on:
            - mongo
            - redis
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - vcf-mongodb:/data/db
    redis:
        container_name: redis
        image: redis
        ports:
            - "6379:6379"
volumes:
    vcf-mongodb:
    vcf-storage:
